"""remove user_id title_rating

Revision ID: 51efe9c2e474
Revises: 8e665edda88a
Create Date: 2023-12-19 18:23:37.104225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51efe9c2e474'
down_revision: Union[str, None] = '8e665edda88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_titles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='user_titles_title_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_titles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_titles_pkey')
    )
    op.create_table('remanga_title_comments_ratings_comments_likes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title_comments_ratings_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['remanga_comment.id'], name='remanga_title_comments_ratings_comments_likes_comment_id_fkey'),
    sa.ForeignKeyConstraint(['title_comments_ratings_id'], ['remanga_title_comments_ratings.id'], name='remanga_title_comments_ratings_c_title_comments_ratings_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_ratings_comments_likes_pkey')
    )
    op.create_table('remanga_chapters',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('remanga_chapters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tome', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_chapters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('remanga_title',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('remanga_title_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rus_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dir_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manga_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('count_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count_bookmarks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count_chapters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('remanga_title_comments_ratings',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('remanga_title_comments_ratings_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_ratings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('remanga_title_categories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('categories_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['remanga_categories.id'], name='remanga_title_categories_categories_id_fkey'),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_categories_title_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remanga_title_categories_pkey')
    )
    op.create_table('remanga_title_genres',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('genres_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genres_id'], ['remanga_genres.id'], name='remanga_title_genres_genres_id_fkey'),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_genres_title_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remanga_title_genres_pkey')
    )
    op.create_table('remanga_title_rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_rating_pkey')
    )
    op.create_table('remanga_rating',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('remanga_rating_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_rating_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_ratings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rating_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['remanga_rating.id'], name='user_ratings_rating_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_ratings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_ratings_pkey')
    )
    op.create_table('remanga_categories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_categories_pkey')
    )
    op.create_table('remanga_title_chapters',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('chapters_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapters_id'], ['remanga_chapters.id'], name='remanga_title_chapters_chapters_id_fkey'),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_chapters_title_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remanga_title_chapters_pkey')
    )
    op.create_table('remanga_genres',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_genres_pkey')
    )
    op.create_table('remanga_comment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('remanga_comment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='remanga_comment_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remanga_comment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('remanga_title_comments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['remanga_comment.id'], name='remanga_title_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_comments_title_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_pkey')
    )
    op.create_table('remanga_title_comments_ratings_comments_dislikes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title_comments_ratings_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['remanga_comment.id'], name='remanga_title_comments_ratings_comments_dislike_comment_id_fkey'),
    sa.ForeignKeyConstraint(['title_comments_ratings_id'], ['remanga_title_comments_ratings.id'], name='remanga_title_comments_ratings__title_comments_ratings_id_fkey1'),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_ratings_comments_dislikes_pkey')
    )
    op.create_table('user_titles_comments_ratings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title_comments_ratings_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['title_comments_ratings_id'], ['remanga_rating.id'], name='user_titles_comments_ratings_rating_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_titles_comments_ratings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_titles_comments_ratings_pkey')
    )
    # ### end Alembic commands ###
