"""User create

Revision ID: f09829aea49c
Revises: 
Create Date: 2023-12-15 13:42:27.519203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f09829aea49c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remanga_title_chapters',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chapters_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapters_id'], ['remanga_chapters.id'], name='remanga_title_chapte_chapters_id_5a7f5e46_fk_remanga_c', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_chapters_title_id_9a405e2a_fk_remanga_title_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_chapters_pkey'),
    sa.UniqueConstraint('title_id', 'chapters_id', name='remanga_title_chapters_title_id_chapters_id_8cbd839b_uniq')
    )
    op.create_index('remanga_title_chapters_title_id_9a405e2a', 'remanga_title_chapters', ['title_id'], unique=False)
    op.create_index('remanga_title_chapters_chapters_id_5a7f5e46', 'remanga_title_chapters', ['chapters_id'], unique=False)
    op.create_table('auth_user_titles_comments_ratings',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title_comments_ratings_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['title_comments_ratings_id'], ['remanga_title_comments_ratings.id'], name='auth_user_titles_com_title_comments_ratin_4eb24492_fk_remanga_t', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_titles_com_user_id_ddc28c87_fk_auth_user', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_titles_comments_ratings_pkey'),
    sa.UniqueConstraint('user_id', 'title_comments_ratings_id', name='auth_user_titles_comment_user_id_title_comments_r_cf536fe3_uniq')
    )
    op.create_index('auth_user_titles_comments_ratings_user_id_ddc28c87', 'auth_user_titles_comments_ratings', ['user_id'], unique=False)
    op.create_index('auth_user_titles_comments__title_comments_ratings_id_4eb24492', 'auth_user_titles_comments_ratings', ['title_comments_ratings_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_user_titles',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='auth_user_titles_title_id_208a846c_fk_remanga_title_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_titles_user_id_e98c34b1_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_titles_pkey'),
    sa.UniqueConstraint('user_id', 'title_id', name='auth_user_titles_user_id_title_id_51783eab_uniq')
    )
    op.create_index('auth_user_titles_user_id_e98c34b1', 'auth_user_titles', ['user_id'], unique=False)
    op.create_index('auth_user_titles_title_id_208a846c', 'auth_user_titles', ['title_id'], unique=False)
    op.create_table('remanga_title_comments_ratings',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_ratings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('remanga_chapters',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tome', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='remanga_chapters_pkey')
    )
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('remanga_title_comments_ratings_comments_likes',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_comments_ratings_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['remanga_comment.id'], name='remanga_title_commen_comment_id_9f691905_fk_remanga_c', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['title_comments_ratings_id'], ['remanga_title_comments_ratings.id'], name='remanga_title_commen_title_comments_ratin_75204558_fk_remanga_t', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_ratings_comments_likes_pkey'),
    sa.UniqueConstraint('title_comments_ratings_id', 'comment_id', name='remanga_title_comments_r_title_comments_ratings_i_65ecc5d7_uniq')
    )
    op.create_index('remanga_title_comments_rat_title_comments_ratings_id_75204558', 'remanga_title_comments_ratings_comments_likes', ['title_comments_ratings_id'], unique=False)
    op.create_index('remanga_title_comments_rat_comment_id_9f691905', 'remanga_title_comments_ratings_comments_likes', ['comment_id'], unique=False)
    op.create_table('remanga_title_categories',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('categories_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['remanga_categories.id'], name='remanga_title_catego_categories_id_befe2a70_fk_remanga_c', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_categories_title_id_48a7b83d_fk_remanga_title_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_categories_pkey'),
    sa.UniqueConstraint('title_id', 'categories_id', name='remanga_title_categories_title_id_categories_id_bb8a642c_uniq')
    )
    op.create_index('remanga_title_categories_title_id_48a7b83d', 'remanga_title_categories', ['title_id'], unique=False)
    op.create_index('remanga_title_categories_categories_id_befe2a70', 'remanga_title_categories', ['categories_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('remanga_title_comments',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['remanga_comment.id'], name='remanga_title_commen_comment_id_13f25900_fk_remanga_c', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_comments_title_id_7d872a75_fk_remanga_title_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_pkey'),
    sa.UniqueConstraint('title_id', 'comment_id', name='remanga_title_comments_title_id_comment_id_17fbc50c_uniq')
    )
    op.create_index('remanga_title_comments_title_id_7d872a75', 'remanga_title_comments', ['title_id'], unique=False)
    op.create_index('remanga_title_comments_comment_id_13f25900', 'remanga_title_comments', ['comment_id'], unique=False)
    op.create_table('auth_user_ratings',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rating_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['remanga_rating.id'], name='auth_user_ratings_rating_id_3a5e956e_fk_remanga_rating_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_ratings_user_id_b9cf3e40_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_ratings_pkey'),
    sa.UniqueConstraint('user_id', 'rating_id', name='auth_user_ratings_user_id_rating_id_6f43a109_uniq')
    )
    op.create_index('auth_user_ratings_user_id_b9cf3e40', 'auth_user_ratings', ['user_id'], unique=False)
    op.create_index('auth_user_ratings_rating_id_3a5e956e', 'auth_user_ratings', ['rating_id'], unique=False)
    op.create_table('remanga_title_genres',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('genres_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genres_id'], ['remanga_genres.id'], name='remanga_title_genres_genres_id_15d54ed5_fk_remanga_genres_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['title_id'], ['remanga_title.id'], name='remanga_title_genres_title_id_cd74505c_fk_remanga_title_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_genres_pkey'),
    sa.UniqueConstraint('title_id', 'genres_id', name='remanga_title_genres_title_id_genres_id_642986a9_uniq')
    )
    op.create_index('remanga_title_genres_title_id_cd74505c', 'remanga_title_genres', ['title_id'], unique=False)
    op.create_index('remanga_title_genres_genres_id_15d54ed5', 'remanga_title_genres', ['genres_id'], unique=False)
    op.create_table('remanga_categories',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='remanga_categories_pkey')
    )
    op.create_table('remanga_title',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('rus_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dir_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manga_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('issue_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count_chapters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('count_rating', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('count_bookmarks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='remanga_title_pkey')
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq')
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('remanga_genres',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='remanga_genres_pkey')
    )
    op.create_table('remanga_rating',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='remanga_rating_pkey')
    )
    op.create_table('remanga_title_comments_ratings_comments_dislikes',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title_comments_ratings_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['remanga_comment.id'], name='remanga_title_commen_comment_id_aa73525e_fk_remanga_c', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['title_comments_ratings_id'], ['remanga_title_comments_ratings.id'], name='remanga_title_commen_title_comments_ratin_b2f63442_fk_remanga_t', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_title_comments_ratings_comments_dislikes_pkey'),
    sa.UniqueConstraint('title_comments_ratings_id', 'comment_id', name='remanga_title_comments_r_title_comments_ratings_i_0ddc310d_uniq')
    )
    op.create_index('remanga_title_comments_rat_title_comments_ratings_id_b2f63442', 'remanga_title_comments_ratings_comments_dislikes', ['title_comments_ratings_id'], unique=False)
    op.create_index('remanga_title_comments_rat_comment_id_aa73525e', 'remanga_title_comments_ratings_comments_dislikes', ['comment_id'], unique=False)
    op.create_table('remanga_comment',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], name='remanga_comment_author_id_c4dc51c8_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='remanga_comment_pkey')
    )
    op.create_index('remanga_comment_author_id_c4dc51c8', 'remanga_comment', ['author_id'], unique=False)
    # ### end Alembic commands ###
